// <auto-generated />
using Buzr.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Buzr.Migrations
{
    [DbContext(typeof(CommentContext))]
    [Migration("20181114141557_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Buzr.Models.CommentReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommentId");

                    b.Property<string>("CommentText");

                    b.Property<string>("ReplyText");

                    b.HasKey("Id");

                    b.ToTable("CommentReplies");
                });
#pragma warning restore 612, 618
        }
    }
}
